
on:
  workflow_call:
    inputs:
      terraformPath:
        required: true
        type: string
      targetEnvironment:
        required: true
        type: string
    # secrets:
    #   envPAT:
    #     required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.targetEnvironment }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        #working-directory: './tf-test'
        
    steps:
    # Authentication
    - name: OIDC Azure Login
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        enable-AzPSSession: true
        # allow-no-subscriptions: true
    
    - name: Set environment variables
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      run: |
        TAG_NAME=${GITHUB_REF#refs/*/}
        echo "ENVIRONMENT=${TAG_NAME:4}" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=$(ARM_CLIENT_ID)" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=$(ARM_TENANT_ID)" >> $GITHUB_ENV

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses:  hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.7"

    - name: Terraform init
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        cd tf-test
        terraform init 
        # -input=false \
        # -backend-config="resource_group_name=rg-terraform-001" \
        # -backend-config="storage_account_name=$TF_STORAGE_ACCOUNT" \
        # -backend-config="container_name=tfstate" \
        # -backend-config="key=$ENVIRONMENT.terraform.tfstate"
      #working-directory: '${{ github.workspace }}/tf-test'

    - name: Terraform plan
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        cd tf-test
        terraform plan
      #working-directory: '${{ github.workspace }}/tf-test'

    - name: Apply Terraform
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        terraform apply \
        -input=false \
        -auto-approve \
        # -var="environment=$ENVIRONMENT"
      working-directory: '${{ github.workspace }}/tf-test'
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        terraform init
      working-directory: '${{ github.workspace }}/tf-test'

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt #-check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        terraform plan
      working-directory: '${{ github.workspace }}/tf-test'

      # On push to master, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". 
      #See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks

    - name: Terraform Apply
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        terraform apply -auto-approve
      working-directory: '${{ github.workspace }}/tf-test'