name: sbx Apply to Example
run-name: e2etesting

on:
  push:    
    branches:      
      - 'e2etesting'
  workflow_dispatch:
    inputs:
      version:
        description: The "version" tag to deploy
        required: false
        default: sbx

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  preConfig:
    runs-on: ubuntu-latest
    outputs:
      AZURE_CLIENT_ID: ${{ steps.preConfigStep.outputs.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ steps.preConfigStep.outputs.AZURE_TENANT_ID }}
    steps:
      - name: preConfig inputs passed to the reusable workflow
        id: preConfigStep
        run: |
          echo "AZURE_CLIENT_ID=$AZURE_CLIENT_ID" >> $GITHUB_OUTPUT
          echo "AZURE_TENANT_ID=$AZURE_TENANT_ID" >> $GITHUB_OUTPUT

  deploy:
    name: Apply ${{ inputs.version }} to sbx
    needs: [preConfig]
    uses: ./.github/workflows/pipeline-apply.yml # my-internal/azure-workflows/.github/workflows/pipeline-apply.yml@main # v2.0.0
    with:
      cloud_provider: azure
      azure_client_id: '${{ needs.preConfig.outputs.AZURE_CLIENT_ID }}' # ghe-npd-action1
      azure_tenant_id: '${{ needs.preConfig.outputs.AZURE_TENANT_ID }}'
      environment_name: sbx # <NDP_or_PRO>
      optfile_path: optfiles/sbx.json # optfiles/_opt_file_example.yml
      optfile_runner: ubuntu-latest # ubuntu-latest 
      # ref: e2etesting # ${{ inputs.version }} # <place branch or tag name containing your released code>
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.TF_APP_PRIVATE_KEY }}

  # destroy:
  #   name: Destroy ${{ inputs.version }} to sbx
  #   needs: [deploy, ]
  #   # # if: ${{ github.ref == 'refs/heads/workflows' && inputs.version != '' }}
  #   uses: ./.github/workflows/pipeline-destroy.yml # my-internal/azure-workflows/.github/workflows/pipeline-apply.yml@main # v2.0.0
  #   with:
  #     cloud_provider: azure
  #     azure_client_id: f69cdf15-340f-4e53-8a28-b6f8a4d9a21d # ghe-npd-action
  #     azure_tenant_id: 81eb6a17-7dfc-44e0-abf2-9ec81d33578b
  #     environment_name: sbx # <NDP_or_PRO>
  #     optfile_path: optfiles/sbx.json # optfiles/_opt_file_example.yml
  #     optfile_runner: ubuntu-latest # ubuntu-latest 
  #     ref: e2etesting # ${{ inputs.version }} # <place branch or tag name containing your released code>
  #   secrets:
  #     APP_PRIVATE_KEY: ${{ secrets.TF_APP_PRIVATE_KEY }}