name: get jwt token example
run-name: get jwt token to Example

on:
  push:    
    branches:      
      - 'workflows'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
jobs:
  demo_app_authentication:
    runs-on: ubuntu-latest
    environment: 
      name: sbx
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 1129019
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: elsalvos-org

      - name: Use the token
        env:
          app-id: 1129019
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: elsalvos-org
        run: |
          gh api octocat
