on:
  push:    
    branches:      
      - 'vending-001'
    # paths:
    #   - 'workload/build/**/*.yml'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}, ${{ inputs.logLevel }} ==="
        echo "Tags: ${{ github.event.inputs.tags }}, ${{ inputs.tags }} ===" 
