name: deploy policies

on:
  push:    
    branches:      
      - 'test-env-vars'
  workflow_dispatch:

jobs:
  plan:
    permissions:
        id-token: write
        contents: read
    uses: './.github/workflows/plan.yml'
    with:
      terraformPath: ./terraform
      targetEnvironment : dev-apply
    secrets: inherit
