name: deploy policies

on:
  push:    
    branches:      
      - 'test-env-vars'
    paths: 
      - ./terraform/*
  workflow_dispatch:

jobs:

  run-terraform-deployment:
    name: terraform deployment
    # needs: [call-plan]
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/apply.yml
    with:
      terraformPath: ./terraform
      targetEnvironment: dev-apply
    secrets: inherit
    
  # call-plan:
  #   permissions:
  #     id-token: write
  #     contents: read
  #     pull-requests: write
  #   uses: ./.github/workflows/plan.yml
  #   with:
  #     terraformPath: ./terraform
  #     targetEnvironment: dev-plan
  #   secrets: inherit
