name: deploy policies

on:
  push:    
    branches:      
      - 'test-env-vars'
  workflow_dispatch:

jobs:
  tfplan:
    permissions:
        id-token: write
        contents: read
        # pull-requests: write
    uses: ./.github/workflows/plan.yml
    with:
      terraformPath: ./terraform # .github/labeler.yml
      targetEnvironment : dev-plan
    secrets: inherit

  tfapply:
    permissions:
        id-token: write
        contents: read
        # pull-requests: write
    uses:  ./.github/workflows/apply.yml # octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      terraformPath: ./terraform # .github/labeler.yml
      targetEnvironment: dev-apply
    secrets: inherit