
on:
  workflow_call:
    inputs:
      tf-planPath:
        required: true
        type: string
      targetEnvironment:
        required: true
        type: string
    # secrets:
    #   envPAT:
    #     required: true

jobs:
  tf-plan:
    name: 'tf-plan'
    runs-on: ubuntu-latest
    environment: ${{ inputs.targetEnvironment }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        #working-directory: './tf-test'
        
    steps:
    # Authentication
    - name: OIDC Azure Login
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        enable-AzPSSession: true
        # allow-no-subscriptions: true
    
    - name: Set environment variables
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      run: |
        TAG_NAME=${GITHUB_REF#refs/*/}
        echo "ENVIRONMENT=${TAG_NAME:4}" >> $GITHUB_ENV
        echo "ARM_CLIENT_ID=$(ARM_CLIENT_ID)" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=$(ARM_TENANT_ID)" >> $GITHUB_ENV

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of tf-plan CLI and configure the tf-plan CLI configuration file with a tf-plan Cloud user API token
    - name: Setup tf-plan
      uses:  hashicorp/setup-tf-plan@v3
      with:
        tf-plan_version: "1.5.7"

    - name: tf-plan init
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        cd tf-test
        tf-plan init 
        # -input=false \
        # -backend-config="resource_group_name=rg-tf-plan-001" \
        # -backend-config="storage_account_name=$TF_STORAGE_ACCOUNT" \
        # -backend-config="container_name=tfstate" \
        # -backend-config="key=$ENVIRONMENT.tf-plan.tfstate"
      #working-directory: '${{ github.workspace }}/tf-test'

    - name: tf-plan plan
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        cd tf-test
        tf-plan plan
      #working-directory: '${{ github.workspace }}/tf-test'

    - name: Apply tf-plan
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        tf-plan apply \
        -input=false \
        -auto-approve \
        # -var="environment=$ENVIRONMENT"
      working-directory: '${{ github.workspace }}/tf-test'
      
    # Initialize a new or existing tf-plan working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: tf-plan Init
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        tf-plan init
      working-directory: '${{ github.workspace }}/tf-test'

    # Checks that all tf-plan configuration files adhere to a canonical format
    - name: tf-plan Format
      run: tf-plan fmt #-check

    # Generates an execution plan for tf-plan
    - name: tf-plan Plan
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        tf-plan plan
      working-directory: '${{ github.workspace }}/tf-test'

      # On push to master, build or change infrastructure according to tf-plan configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "tf-plan Cloud". 
      #See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks

    - name: tf-plan Apply
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        #TF_STORAGE_ACCOUNT: ${{ secrets.TF_STORAGE_ACCOUNT }}
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        export ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)
        tf-plan apply -auto-approve
      working-directory: '${{ github.workspace }}/tf-test'