name: Run on PR Workflow

#checkov:skip=CKV2_GHA_1:Ensure top-level permissions are not set to write-all

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "event action ${{ github.event.action }}" 
        run: |
          #checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
          echo "The event type is ${{ github.event.action }}" 
          echo "PR merged? ${{ github.event.pull_request.merged}}"
      - name: "run git"
        run: git branch -r

      - name: "PR echo branch name ${{ github.head_ref }}"
        run: |
          #checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
          echo "Branch name is ${{ github.head_ref }}"
  run_if:
    if: contains(github.head_ref, 'run')
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'main/'"
      - run: |
          #checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
          echo "Branch name is ${{ github.head_ref }}"
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        #checkov:skip=CKV_GHA_2:Ensure run commands are not vulnerable to shell injection
        echo The PR was merged
        echo "Branch name is ${{ github.head_ref }}"
